---
title: "Cell types"
output: html_document
date: "2025-05-22"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(Seurat)
library(dplyr)
library(tidyverse)
library(readxl)
library(ComplexHeatmap)
library(openxlsx)
```

```{r}
seurat_integrated_ME <- readRDS("~/R/Downloads/Seurat_Integrated_ME.rds")
```

7 dpi

```{r}
Idents(seurat_integrated_ME) <- "time"

astro <- subset(seurat_integrated_ME, subset = celltype == "Astrocytes")
DEG_astro <- FindMarkers(astro, ident.1 = "7dpi", ident.2 = "Uninjured", logfc.threshold = 0, min.pct = 0.05, test.use = "MAST")
DEG_astro$Gene <- rownames(DEG_astro)
DEG_astro$celltype <- "Astrocytes"

neuron <- subset(seurat_integrated_ME, subset = celltype == "Neurons")
DEG_neuron <- FindMarkers(neuron, ident.1 = "7dpi", ident.2 = "Uninjured", logfc.threshold = 0, min.pct = 0.05, test.use = "MAST")
DEG_neuron$Gene <- rownames(DEG_neuron)
DEG_neuron$celltype <- "Neurons"

microglia <- subset(seurat_integrated_ME, subset = celltype == "Microglia")
DEG_microglia <- FindMarkers(microglia, ident.1 = "7dpi", ident.2 = "Uninjured", logfc.threshold = 0, min.pct = 0.05, test.use = "MAST")
DEG_microglia$Gene <- rownames(DEG_microglia)
DEG_microglia$celltype <- "Microglia"

opc <- subset(seurat_integrated_ME, subset = celltype == "OPCs")
DEG_opc <- FindMarkers(opc, ident.1 = "7dpi", ident.2 = "Uninjured", logfc.threshold = 0, min.pct = 0.05, test.use = "MAST")
DEG_opc$Gene <- rownames(DEG_opc)
DEG_opc$celltype <- "OPCs"

ependymal <- subset(seurat_integrated_ME, subset = celltype == "Ependymal cells")
DEG_ependymal <- FindMarkers(ependymal, ident.1 = "7dpi", ident.2 = "Uninjured", logfc.threshold = 0, min.pct = 0.05, test.use = "MAST")
DEG_ependymal$Gene <- rownames(DEG_ependymal)
DEG_ependymal$celltype <- "Ependymal cells"

endo <- subset(seurat_integrated_ME, subset = celltype == "Endothelial cells")
DEG_endo <- FindMarkers(endo, ident.1 = "7dpi", ident.2 = "Uninjured", logfc.threshold = 0, min.pct = 0.05, test.use = "MAST")
DEG_endo$Gene <- rownames(DEG_endo)
DEG_endo$celltype <- "Endothelial cells"

vascular <- subset(seurat_integrated_ME, subset = celltype == "Vascular cells")
DEG_vascular <- FindMarkers(vascular, ident.1 = "7dpi", ident.2 = "Uninjured", logfc.threshold = 0, min.pct = 0.05, test.use = "MAST")
DEG_vascular$Gene <- rownames(DEG_vascular)
DEG_vascular$celltype <- "Vascular cells"

immune <- subset(seurat_integrated_ME, subset = celltype == "Immune cells")
DEG_immune<- FindMarkers(immune, ident.1 = "7dpi", ident.2 = "Uninjured", logfc.threshold = 0, min.pct = 0.05, test.use = "MAST")
DEG_immune$Gene <- rownames(DEG_immune)
DEG_immune$celltype <- "Immune cells"

oligodendrocyte <- subset(seurat_integrated_ME, subset = celltype == "Oligodendrocytes")
DEG_oligodendrocyte <- FindMarkers(oligodendrocyte, ident.1 = "7dpi", ident.2 = "Uninjured", logfc.threshold = 0, min.pct = 0.05, test.use = "MAST")
DEG_oligodendrocyte$Gene <- rownames(DEG_oligodendrocyte)
DEG_oligodendrocyte$celltype <- "Oligodendrocytes"

combined_results <- bind_rows(DEG_astro, DEG_neuron, DEG_microglia, DEG_opc, DEG_oligodendrocyte, DEG_immune, DEG_vascular, DEG_ependymal, DEG_endo)

combined_results$time <- "7 dpi"

write.xlsx(combined_results, "~/R/Data/DEG_Celltype_7dpi.xlsx")
```

4-6 wpi

```{r}
Idents(seurat_integrated_ME) <- "time"

astro <- subset(seurat_integrated_ME, subset = celltype == "Astrocytes")
DEG_astro <- FindMarkers(astro, ident.1 = "4-6 wpi", ident.2 = "Uninjured", logfc.threshold = 0, min.pct = 0.05, test.use = "MAST")
DEG_astro$Gene <- rownames(DEG_astro)
DEG_astro$celltype <- "Astrocytes"

neuron <- subset(seurat_integrated_ME, subset = celltype == "Neurons")
DEG_neuron <- FindMarkers(neuron, ident.1 = "4-6 wpi", ident.2 = "Uninjured", logfc.threshold = 0, min.pct = 0.05, test.use = "MAST")
DEG_neuron$Gene <- rownames(DEG_neuron)
DEG_neuron$celltype <- "Neurons"

microglia <- subset(seurat_integrated_ME, subset = celltype == "Microglia")
DEG_microglia <- FindMarkers(microglia, ident.1 = "4-6 wpi", ident.2 = "Uninjured", logfc.threshold = 0, min.pct = 0.05, test.use = "MAST")
DEG_microglia$Gene <- rownames(DEG_microglia)
DEG_microglia$celltype <- "Microglia"

opc <- subset(seurat_integrated_ME, subset = celltype == "OPCs")
DEG_opc <- FindMarkers(opc, ident.1 = "4-6 wpi", ident.2 = "Uninjured", logfc.threshold = 0, min.pct = 0.05, test.use = "MAST")
DEG_opc$Gene <- rownames(DEG_opc)
DEG_opc$celltype <- "OPCs"

ependymal <- subset(seurat_integrated_ME, subset = celltype == "Ependymal cells")
DEG_ependymal <- FindMarkers(ependymal, ident.1 = "4-6 wpi", ident.2 = "Uninjured", logfc.threshold = 0, min.pct = 0.05, test.use = "MAST")
DEG_ependymal$Gene <- rownames(DEG_ependymal)
DEG_ependymal$celltype <- "Ependymal cells"

endo <- subset(seurat_integrated_ME, subset = celltype == "Endothelial cells")
DEG_endo <- FindMarkers(endo, ident.1 = "4-6 wpi", ident.2 = "Uninjured", logfc.threshold = 0, min.pct = 0.05, test.use = "MAST")
DEG_endo$Gene <- rownames(DEG_endo)
DEG_endo$celltype <- "Endothelial cells"

vascular <- subset(seurat_integrated_ME, subset = celltype == "Vascular cells")
DEG_vascular <- FindMarkers(vascular, ident.1 = "4-6 wpi", ident.2 = "Uninjured", logfc.threshold = 0, min.pct = 0.05, test.use = "MAST")
DEG_vascular$Gene <- rownames(DEG_vascular)
DEG_vascular$celltype <- "Vascular cells"

immune <- subset(seurat_integrated_ME, subset = celltype == "Immune cells")
DEG_immune<- FindMarkers(immune, ident.1 = "4-6 wpi", ident.2 = "Uninjured", logfc.threshold = 0, min.pct = 0.05, test.use = "MAST")
DEG_immune$Gene <- rownames(DEG_immune)
DEG_immune$celltype <- "Immune cells"

oligodendrocyte <- subset(seurat_integrated_ME, subset = celltype == "Oligodendrocytes")
DEG_oligodendrocyte <- FindMarkers(oligodendrocyte, ident.1 = "4-6 wpi", ident.2 = "Uninjured", logfc.threshold = 0, min.pct = 0.05, test.use = "MAST")
DEG_oligodendrocyte$Gene <- rownames(DEG_oligodendrocyte)
DEG_oligodendrocyte$celltype <- "Oligodendrocytes"

combined_results <- bind_rows(DEG_astro, DEG_neuron, DEG_microglia, DEG_opc, DEG_oligodendrocyte, DEG_immune, DEG_vascular, DEG_ependymal, DEG_endo)

combined_results$time <- "4-6 wpi"

write.xlsx(combined_results, "~/R/Data/DEG_Celltype_Chronic.xlsx")

```

Data for other time points - At cell type level

```{r}
Idents(seurat_integrated_ME) <- "time"

astro <- subset(seurat_integrated_ME, subset = celltype == "Astrocytes")
DEG_astro <- FindMarkers(astro, ident.1 = "1dpi", ident.2 = "Uninjured", logfc.threshold = 0, min.pct = 0.05, test.use = "MAST")
DEG_astro$Gene <- rownames(DEG_astro)
DEG_astro$celltype <- "Astrocytes"

neuron <- subset(seurat_integrated_ME, subset = celltype == "Neurons")
DEG_neuron <- FindMarkers(neuron, ident.1 = "1dpi", ident.2 = "Uninjured", logfc.threshold = 0, min.pct = 0.05, test.use = "MAST")
DEG_neuron$Gene <- rownames(DEG_neuron)
DEG_neuron$celltype <- "Neurons"

microglia <- subset(seurat_integrated_ME, subset = celltype == "Microglia")
DEG_microglia <- FindMarkers(microglia, ident.1 = "1dpi", ident.2 = "Uninjured", logfc.threshold = 0, min.pct = 0.05, test.use = "MAST")
DEG_microglia$Gene <- rownames(DEG_microglia)
DEG_microglia$celltype <- "Microglia"

opc <- subset(seurat_integrated_ME, subset = celltype == "OPCs")
DEG_opc <- FindMarkers(opc, ident.1 = "1dpi", ident.2 = "Uninjured", logfc.threshold = 0, min.pct = 0.05, test.use = "MAST")
DEG_opc$Gene <- rownames(DEG_opc)
DEG_opc$celltype <- "OPCs"

ependymal <- subset(seurat_integrated_ME, subset = celltype == "Ependymal cells")
DEG_ependymal <- FindMarkers(ependymal, ident.1 = "1dpi", ident.2 = "Uninjured", logfc.threshold = 0, min.pct = 0.05, test.use = "MAST")
DEG_ependymal$Gene <- rownames(DEG_ependymal)
DEG_ependymal$celltype <- "Ependymal cells"

endo <- subset(seurat_integrated_ME, subset = celltype == "Endothelial cells")
DEG_endo <- FindMarkers(endo, ident.1 = "1dpi", ident.2 = "Uninjured", logfc.threshold = 0, min.pct = 0.05, test.use = "MAST")
DEG_endo$Gene <- rownames(DEG_endo)
DEG_endo$celltype <- "Endothelial cells"

vascular <- subset(seurat_integrated_ME, subset = celltype == "Vascular cells")
DEG_vascular <- FindMarkers(vascular, ident.1 = "1dpi", ident.2 = "Uninjured", logfc.threshold = 0, min.pct = 0.05, test.use = "MAST")
DEG_vascular$Gene <- rownames(DEG_vascular)
DEG_vascular$celltype <- "Vascular cells"

immune <- subset(seurat_integrated_ME, subset = celltype == "Immune cells")
DEG_immune<- FindMarkers(immune, ident.1 = "1dpi", ident.2 = "Uninjured", logfc.threshold = 0, min.pct = 0.05, test.use = "MAST")
DEG_immune$Gene <- rownames(DEG_immune)
DEG_immune$celltype <- "Immune cells"

oligodendrocyte <- subset(seurat_integrated_ME, subset = celltype == "Oligodendrocytes")
DEG_oligodendrocyte <- FindMarkers(oligodendrocyte, ident.1 = "1dpi", ident.2 = "Uninjured", logfc.threshold = 0, min.pct = 0.05, test.use = "MAST")
DEG_oligodendrocyte$Gene <- rownames(DEG_oligodendrocyte)
DEG_oligodendrocyte$celltype <- "Oligodendrocytes"

combined_results <- bind_rows(DEG_astro, DEG_neuron, DEG_microglia, DEG_opc, DEG_oligodendrocyte, DEG_immune, DEG_vascular, DEG_ependymal, DEG_endo)

combined_results$time <- "1 dpi"

write.xlsx(combined_results, "~/R/Data/DEG_Celltype_1dpi.xlsx")
```


```{r}
Idents(seurat_integrated_ME) <- "time"

astro <- subset(seurat_integrated_ME, subset = celltype == "Astrocytes")
DEG_astro <- FindMarkers(astro, ident.1 = "21 dpi", ident.2 = "Uninjured", logfc.threshold = 0, min.pct = 0.05, test.use = "MAST")
DEG_astro$Gene <- rownames(DEG_astro)
DEG_astro$celltype <- "Astrocytes"

neuron <- subset(seurat_integrated_ME, subset = celltype == "Neurons")
DEG_neuron <- FindMarkers(neuron, ident.1 = "21 dpi", ident.2 = "Uninjured", logfc.threshold = 0, min.pct = 0.05, test.use = "MAST")
DEG_neuron$Gene <- rownames(DEG_neuron)
DEG_neuron$celltype <- "Neurons"

microglia <- subset(seurat_integrated_ME, subset = celltype == "Microglia")
DEG_microglia <- FindMarkers(microglia, ident.1 = "21 dpi", ident.2 = "Uninjured", logfc.threshold = 0, min.pct = 0.05, test.use = "MAST")
DEG_microglia$Gene <- rownames(DEG_microglia)
DEG_microglia$celltype <- "Microglia"

opc <- subset(seurat_integrated_ME, subset = celltype == "OPCs")
DEG_opc <- FindMarkers(opc, ident.1 = "21 dpi", ident.2 = "Uninjured", logfc.threshold = 0, min.pct = 0.05, test.use = "MAST")
DEG_opc$Gene <- rownames(DEG_opc)
DEG_opc$celltype <- "OPCs"

ependymal <- subset(seurat_integrated_ME, subset = celltype == "Ependymal cells")
DEG_ependymal <- FindMarkers(ependymal, ident.1 = "21 dpi", ident.2 = "Uninjured", logfc.threshold = 0, min.pct = 0.05, test.use = "MAST")
DEG_ependymal$Gene <- rownames(DEG_ependymal)
DEG_ependymal$celltype <- "Ependymal cells"

endo <- subset(seurat_integrated_ME, subset = celltype == "Endothelial cells")
DEG_endo <- FindMarkers(endo, ident.1 = "21 dpi", ident.2 = "Uninjured", logfc.threshold = 0, min.pct = 0.05, test.use = "MAST")
DEG_endo$Gene <- rownames(DEG_endo)
DEG_endo$celltype <- "Endothelial cells"

vascular <- subset(seurat_integrated_ME, subset = celltype == "Vascular cells")
DEG_vascular <- FindMarkers(vascular, ident.1 = "21 dpi", ident.2 = "Uninjured", logfc.threshold = 0, min.pct = 0.05, test.use = "MAST")
DEG_vascular$Gene <- rownames(DEG_vascular)
DEG_vascular$celltype <- "Vascular cells"

immune <- subset(seurat_integrated_ME, subset = celltype == "Immune cells")
DEG_immune<- FindMarkers(immune, ident.1 = "21 dpi", ident.2 = "Uninjured", logfc.threshold = 0, min.pct = 0.05, test.use = "MAST")
DEG_immune$Gene <- rownames(DEG_immune)
DEG_immune$celltype <- "Immune cells"

oligodendrocyte <- subset(seurat_integrated_ME, subset = celltype == "Oligodendrocytes")
DEG_oligodendrocyte <- FindMarkers(oligodendrocyte, ident.1 = "21 dpi", ident.2 = "Uninjured", logfc.threshold = 0, min.pct = 0.05, test.use = "MAST")
DEG_oligodendrocyte$Gene <- rownames(DEG_oligodendrocyte)
DEG_oligodendrocyte$celltype <- "Oligodendrocytes"

combined_results <- bind_rows(DEG_astro, DEG_neuron, DEG_microglia, DEG_opc, DEG_oligodendrocyte, DEG_immune, DEG_vascular, DEG_ependymal, DEG_endo)

combined_results$time <- "21 dpi"

write.xlsx(combined_results, "~/R/Data/DEG_Celltype_21dpi.xlsx")

```

```{r}
genes <- readRDS("~/R/Downloads/Genes_Correlation.rds")

combined_results <- read_excel("~/R/Data/DEG_Celltype_7dpi.xlsx")

combined_results <- combined_results %>%
  filter(Gene %in% genes)

heatmap_data <- combined_results %>%
  dplyr::select(Gene, celltype, avg_log2FC) %>%
  pivot_wider(names_from = celltype, values_from = avg_log2FC) %>%
  column_to_rownames("Gene") %>%
  as.matrix()

heatmap_data[is.na(heatmap_data)] <- 0

heatmap_7dpi <- Heatmap(
  heatmap_data,
  col = circlize::colorRamp2(c(-5, 0, 5), c("blue", "white", "red")),
  row_names_gp = gpar(fontsize = 7),
  column_names_gp = gpar(fontsize = 8),
  name = "log2FC", row_title_side = "left", column_title_side = "bottom", column_names_rot = 90
)

heatmap_7dpi

png("~/R/Figures2/Heatmap_Celltype_7dpi.png",  width = 2500, height = 3500, res = 580)
draw(heatmap_7dpi)
dev.off()
```

```{r}
combined_results <- read_excel("~/R/Data/DEG_Celltype_Chronic.xlsx")

combined_results <- combined_results %>%
  filter(Gene %in% genes)

heatmap_data <- combined_results %>%
  dplyr::select(Gene, celltype, avg_log2FC) %>%
  pivot_wider(names_from = celltype, values_from = avg_log2FC) %>%
  column_to_rownames("Gene") %>%
  as.matrix()

heatmap_data[is.na(heatmap_data)] <- 0

heatmap_chronic <- Heatmap(
  heatmap_data,
  col = circlize::colorRamp2(c(-5, 0, 5), c("blue", "white", "red")),
  row_names_gp = gpar(fontsize = 8),
  column_names_gp = gpar(fontsize = 8),
  name = "log2FC", row_title_side = "right", column_title_side = "bottom", column_names_rot = 90
)

heatmap_chronic

png("~/R/Figures2/Heatmap_Celltype_Chronic.png",  width = 2500, height = 3500, res = 580)
draw(heatmap_chronic)
dev.off()
```
```{r}
library(readxl)
library(dplyr)
library(tidyr)
library(tibble)
library(circlize)
library(ComplexHeatmap)

# Load gene list
genes <- readRDS("~/R/Downloads/Genes_Correlation.rds")

# ---- 7 dpi ----
results_7dpi <- read_excel("~/R/Data/DEG_Celltype_7dpi.xlsx") %>%
  filter(Gene %in% genes)

mat_7dpi <- results_7dpi %>%
  dplyr::select(Gene, celltype, avg_log2FC) %>%
  pivot_wider(names_from = celltype, values_from = avg_log2FC) %>%
  column_to_rownames("Gene")

mat_7dpi[is.na(mat_7dpi)] <- 0

hm_7dpi <- Heatmap(
  as.matrix(mat_7dpi),
  col = colorRamp2(c(-5, 0, 5), c("steelblue", "white", "tomato")),
  name = "log2FC",
  rect_gp = gpar(col = "grey", lwd = 2),
  row_names_gp = gpar(fontsize = 7),
  row_names_side = "left",
  column_names_gp = gpar(fontsize = 7),
  column_names_rot = 90,
  cluster_rows = FALSE,
  cluster_columns = FALSE,
  show_row_names = TRUE,
  column_title = "7 dpi",
  column_title_gp = gpar(fontsize = 10)
)

# ---- Chronic ----
results_chronic <- read_excel("~/R/Data/DEG_Celltype_Chronic.xlsx") %>%
  filter(Gene %in% genes)

mat_chronic <- results_chronic %>%
  dplyr::select(Gene, celltype, avg_log2FC) %>%
  pivot_wider(names_from = celltype, values_from = avg_log2FC) %>%
  column_to_rownames("Gene")

mat_chronic[is.na(mat_chronic)] <- 0

# Align row order with 7 dpi
mat_chronic <- mat_chronic[rownames(mat_7dpi), ]

hm_chronic <- Heatmap(
  as.matrix(mat_chronic),
  col = colorRamp2(c(-5, 0, 5), c("steelblue", "white", "tomato")),
  name = "log2FC",
  rect_gp = gpar(col = "grey", lwd = 2),
  row_names_gp = gpar(fontsize = 7),
  column_names_gp = gpar(fontsize = 7),
  column_names_rot = 90,
  cluster_rows = FALSE,
  cluster_columns = FALSE,
  show_row_names = FALSE,
  column_title = "4-6 wpi",
  column_title_gp = gpar(fontsize = 10)
)

# ---- Final plot ----
png("~/R/Figures2/Heatmap_Celltype_Combined.png", width = 3800, height = 3500, res = 600)
draw(
  hm_7dpi + hm_chronic,
  column_title = "                Expression in different cell types of the final biomarkers",
  column_title_gp = gpar(fontsize = 16, fontface = "bold")
)
dev.off()

```

